# Redis Configuration
enabled: false  # Set to true to enable Redis caching
host: "localhost"
port: 6379
# password: "your_redis_password"  # Uncomment if Redis requires authentication
# database: 0  # Redis database number (0-15)